steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
             'us-central1-docker.pkg.dev/${PROJECT_ID}/cloudrun-art/cloudrun-art:${SHORT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/cloudrun-art/cloudrun-art:${SHORT_SHA}']

  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >
        gcloud config set project ${PROJECT_ID}    
        gcloud compute ssh gitlab-runner --zone us-central1-a --quiet
        gcloud compute ssh --zone "us-central1-a" "gitlab-runner" --project "iconic-post-406804" --quiet
        
        
       
    entrypoint: bash

  #- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   # entrypoint: gcloud
   # args: ['run', 'deploy', 'cloudrun-demo', '--image', 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloudrun-art/cloudrun-art:${SHORT_SHA}', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
